//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//

import Foundation


//MARK: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: class {
  var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?  { get set }
}
