//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//  Component: Presenter -

import UIKit

class ___VARIABLE_productName:identifier___Presenter{

    weak private var view: ___VARIABLE_productName:identifier___ViewProtocol?

    init(interface: ___VARIABLE_productName:identifier___ViewProtocol) {
        self.view = interface
    }

}
