//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//  Component: View -

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController{

	var viewModel: ___VARIABLE_productName:identifier___ViewModel?

	override func viewDidLoad() {
        super.viewDidLoad()
        viewModel = ___VARIABLE_productName:identifier___ViewModel()
    
        viewModel?.isError.addObserver({ (error) in
            // display error
        })
        
        viewModel?.isLoading.addObserver({ (loading) in
            // display loading
        })
    }
}
