//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//  Component: Interactor -

import UIKit

//MARK: Interactor -
protocol ___VARIABLE_productName:identifier___InteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ___VARIABLE_productName:identifier___InteractorInputProtocol: class {

    var presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorInputProtocol {

    weak var presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol?
}
