//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//  Component: View -

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController, ___VARIABLE_productName:identifier___ViewProtocol {

	var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter = ___VARIABLE_productName:identifier___Presenter(interface: self)
    }

}
