//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//  Component: Protocol -

import Foundation

//Component: Presenter -
protocol ___VARIABLE_productName:identifier___PresenterProtocol: class {
  func test()
}

//Component: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: class {
  var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?  { get set }
  func isLoading(loading : Bool)
  func isError(message : String)
}
